### ISSUE TITLE
Link to external css 

### ISSUE THREAD

**Issue by Sennevds** [sliderweb/Hydrogen#1]
Hi there's a static link to https://sliderweb.ru/plugins/individuart/work/assets/css/work.min.css and this file doesn't exist and i can't find the css file in the theme maybe add the css to the theme?

**Comment by sliderweb** [comment]
Hello!
This bug was fixed. Update or reinstall theme. 
This repo not contain string like "work.min.css" 
If you have installed "Work" Plugin - check plugins configuration. Plugin injecting css to themes.

**Comment by sliderweb** [comment]
Theme rebuild and pushed. Please install CMS updates
